#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
import numpy as np
from nav_msgs.msg import OccupancyGrid, Path
from geometry_msgs.msg import PoseStamped
from PIL import Image

class PathToBitmap(Node):
    def __init__(self):
        super().__init__('path_to_bitmap')

        self.latest_map = None
        self.latest_path_pixels = []

        # Subscribe to the map
        self.map_sub = self.create_subscription(
            OccupancyGrid,
            '/my_costmap',
            self.map_callback,
            10
        )

        # Subscribe to the path generated by your A* path planner
        self.path_sub = self.create_subscription(
            Path,
            '/a_star_path',
            self.path_callback,
            10
        )

        self.get_logger().info("Waiting for map and path...")

    def path_callback(self, msg: Path):
        """Convert nav_msgs/Path into pixel coordinates."""
        if self.latest_map is None:
            return
        
        res = self.latest_map.info.resolution
        origin = self.latest_map.info.origin.position

        path_pixels = []

        for pose in msg.poses:
            # World coordinates
            wx = pose.pose.position.x
            wy = pose.pose.position.y

            # Convert to map pixel coordinates
            px = int((wx - origin.x) / res)
            py = int((wy - origin.y) / res)

            path_pixels.append((px, py))

        self.latest_path_pixels = path_pixels
        self.get_logger().info(f"Received path with {len(path_pixels)} points.")

        self.render_bitmap()

    def map_callback(self, msg: OccupancyGrid):
        self.latest_map = msg
        self.get_logger().info(f"Map received: {msg.info.width}x{msg.info.height}")
        self.render_bitmap()

    def render_bitmap(self):
        """Render map + path to BMP file only when both are available."""
        if self.latest_map is None:
            return

        width = self.latest_map.info.width
        height = self.latest_map.info.height
        grid = np.array(self.latest_map.data).reshape((height, width))

        # Convert occupancy to grayscale image
        image = np.zeros((height, width, 3), dtype=np.uint8)

        image[grid == -1] = [160, 160, 160]   # unknown
        image[grid >= 50] = [0, 0, 0]         # occupied
        image[grid == 0] = [255, 255, 255]    # free

        # -------- DRAW PATH IN RED --------
        for (x, y) in self.latest_path_pixels:
            if 0 <= x < width and 0 <= y < height:
                image[y, x] = [255, 0, 0]

        # -------- DRAW GOAL IN RED --------
        if len(self.latest_path_pixels) > 0:
            gx, gy = self.latest_path_pixels[-1]
            if 0 <= gx < width and 0 <= gy < height:
                image[gy, gx] = [255, 0, 0]

        # Save final BMP
        bmp = Image.fromarray(image)
        filename = "map_with_path.bmp"
        bmp.save(filename)

        self.get_logger().info(f"Bitmap saved: {filename}")


def main(args=None):
    rclpy.init(args=args)
    node = PathToBitmap()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
